config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path_prefix: 'my'
  patch 'users/:id(.:format)', to: 'users#update_donated_date_post_donator', as: 'select_volunteer'
  root 'pages#home'

  get 'pages/home'
  get 'pages/about'
  get 'posts/specific_indexing'
  resources :posts do
    resources :comments
    resources :volunteers, only: %i[create destroy]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
# Model for Post
class Post < ApplicationRecord
  validates :title, presence: true, length: { minimum: 5 }
  validates :description, :bloodtype, :requester, :telephone, presence: true

  belongs_to :user
  has_many :comments, dependent: :destroy

  has_many :volunteers, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  has_many :comments
  has_many :posts

  has_many :volunteers, through: :posts

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  enum role: %i[normal moderator admin]
  after_initialize do
    self.role ||= :normal if new_record?
  end
end

app/models/volunteer.rb
class Volunteer < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:name, :telephone, :bloodtype, :email, :password, :last_donated_date)
    end
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :telephone, :bloodtype, :email, :password, :current_password, :last_donated_date)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[show edit update destroy]
  before_action :find_post, only: %i[create destroy]

  def create
    # Changing create to new
    @comment = @post.comments.create(comment_params)
    # adding new changes to hopefully make this works
    @comment.user = current_user
    # Add name of the user here
    @comment.name = current_user.name

    if @comment.save
      flash[:notice] = 'Comment was posted successfully'
      redirect_to @post
    else
      render 'new'
    end
  end

  def destroy
    @comment = @post.comments.find(params[:id])
    @comment.destroy

    flash[:notice] = 'Comment was deleted successfully'
    redirect_to post_path(@post)
  end

  private

  def find_post
    @post = Post.find_by_id(params[:post_id])
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:post_id, :comment, :user_id, :name)
  end
end

app/controllers/pages_controller.rb
# Controller for managing static pages such as home and main
class PagesController < ApplicationController
  def home; end

  def about; end
end

app/controllers/posts_controller.rb
# Post Controller
class PostsController < ApplicationController
  before_action :find_post, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[index show]

  def index
    @posts = Post.all
  end

  def specific_indexing
    @posts = Post.where(bloodtype: current_user.bloodtype)
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      flash[:notice] = 'Post was successfully created'
      redirect_to @post
    else
      flash[:alert] = 'Post was not created'
      render 'new'
    end
  end

  def show; end

  def edit; end

  def update
    if @post.update(post_params)
      flash[:notice] = 'Post was successfully updated'
      redirect_to @post
    else
      flash[:alert] = 'Post was not updated'
      render 'edit'
    end
  end

  def destroy
    authorize @post
    @post.destroy
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :description, :telephone, :bloodtype, :requester, :user_id)
  end

  def find_post
    @post = Post.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def update_donated_date_post_donator
    @post = Post.find(params[:id])
    @post.update(params.permit(:donator))

    @user = User.find(params[:user_id])
    @user.update(params.permit(:last_donated_date))

    redirect_back(fallback_location: root_path)
  end
end

app/controllers/volunteers_controller.rb
class VolunteersController < ApplicationController
  before_action(only: %i[destroy]) { @volunteer = Volunteer.find(params[:id]) }
  before_action :find_post, only: %i[create destroy]

  def create
    @volunteer = @post.volunteers.create(volunteer_params)
    @volunteer.user = current_user

    if @volunteer.save
      flash[:notice] = 'Your volunteer application has been accepted'
      redirect_back(fallback_location: root_path)
    else
      flash.now[:alert] = 'No response from the server, please try again!'
    end
  end

  def destroy; end

  private

  def find_post
    @post = Post.find_by_id(params[:post_id])
  end

  def volunteer_params
    params.permit(:post_id, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bloodytype_select
    bt = [['AB+', 'AB+'], ['AB-', 'AB-'], ['A+', 'A+'], ['A-', 'A-'],
          ['B+', 'B+'], ['B-', 'B-'], ['O+', 'O+'], ['O-', 'O-']]
    bt
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def bloodytype_select
    bt = [['AB+', 'AB+'], ['AB-', 'AB-'], ['A+', 'A+'], ['A-', 'A-'],
          ['B+', 'B+'], ['B-', 'B-'], ['O+', 'O+'], ['O-', 'O-']]
    bt
  end

  def donator_check(post, current_user)
    date = Date.today << 3
    post.donator.blank? && !current_user.admin? && current_user.last_donated_date < date
  end

  def volunteer_show_check(post, current_user)
    post.donator.blank? && current_user.admin? && Volunteer.exists?(post_id: post)
  end
end

app/views/comments/_comment.html.slim
.container
  .card.mt-4
    .card-body
      h5.card-title
        strong
          = comment.user.name
      h6.card-subtitle.mb-2.text-muted
        em
          = time_ago_in_words(comment.created_at)
      p.card-text.ml-3
        = comment.comment
      - if comment.user == current_user || current_user.admin?
        a.card-link
          = link_to 'Delete', [comment.post, comment], method: :delete, data: { confirm: "Are you sure?" }

app/views/comments/_form.html.slim
= form_with(model: [@post, @post.comments.build], local: true, :html => {class: 'form-horizontal', role: 'form'}) do |f|
    .form
      .row
        .col-lg-12
          .form-group
            .col-lg-12.col-sm-6
              = f.text_area :comment, rows: 2, class: 'form-control', placeholder: 'Add your comment here'
      .form-group
        .col-sm-offset-2.col-sm-10
          = f.submit class: 'btn btn-primary btn-large'

app/views/layouts/_navigation.html.slim
nav.navbar.navbar-expand-lg.navbar-dark.bg-dark
  = link_to 'Blood Society', pages_home_path, class: 'navbar-brand', id: 'logo'
  button.navbar-toggler aria-controls= 'navbarSupportedContent' aria-expanded= 'false' aria-label= ('Toggle navigation') data-target= '#navbarSupportedContent' data-toggle= 'collapse' type= 'button'
    span.navbar-toggler-icon
  #navbarSupportedContent.collapse.navbar-collapse
    ul.navbar-nav.mr-auto
      li.nav-item.active
        - if user_signed_in? && current_user.admin?
          a.nav-link href= posts_path
            | All Posts
            span.sr-only (current)
      - if user_signed_in?
        - if !current_user.admin?
          li.nav-item
            a.nav-link href= posts_specific_indexing_path
              | Your Posts
        li.nav-item
          - if current_user.admin?
            a.nav-link href= new_post_path
              | Create Post
    ul.navbar-nav.navbar-right
      - if user_signed_in?
        li.nav-item.dropdown
          a#navbarDropdown.nav-link.dropdown-toggle aria-expanded= 'false' aria-haspopup= 'true' data-toggle= 'dropdown' href ='#' role= 'button'
            | User Options
          .dropdown-menu aria-labelledby= 'navbarDropdown'
              a.dropdown-item.font-weight-bold = current_user.name
              .dropdown-divider
              a.dropdown-item href= edit_user_registration_path Edit Profile
              a.dropdown-item href= '#' Something else here
      - if user_signed_in?
        = link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link'
      - else
        li.nav-item
          a.nav-link href= new_user_registration_path
            | Sign Up
        li.nav-item
          a.nav-link href= new_user_session_path
            | Sign in

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blood Donation Society</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Baloo+Chettan+2&display=swap' %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= favicon_link_tag asset_path('blood.ico') %>
  </head>
  <body>
    <%= render 'layouts/navigation' %>
    <div class = "container">
      <% flash.each do |name, msg| %>
        <% if name == "alert" %>
          <div class = "alert alert-danger mt-3" role="alert">
            <ul class="pt-3">
            <li><%= msg %></li>
          </ul>
        </div>
        <% else %>
          <div class = "alert alert-info mt-3" role="alert">
            <ul class="pt-3">
            <li><%= msg %></li>
          </ul>
        </div>
        <% end %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/about.html.slim
h1 Pages#about
p Find me in app/views/pages/about.html.erb

app/views/pages/home.html.slim
.jumbotron
  h1.display-4.text-center.font-weight-bold
    | Blood Donation Society
  p.lead.text-center
    | Hold up, we'll be right there
  hr.my-4
  p.text-center.font-weight-bold
    | COMING SOON
  div.text-center
    a.btn.btn-primary.btn-lg[href= pages_about_path role='button']
      | Learn more

app/views/posts/_form.html.slim
= form_with(model: @post, local: true, :html => {class: 'form-horizontal', role: 'form'}) do |f|
  - if @post.errors.any?
    .alert.alert-danger[role= 'alert']
      h3
        = pluralize(@post.errors.count, 'error')
        | prohibited this post from being saved:
      ul
        -@post.errors.full_messages.each do |msg|
          li
            = msg

  .form
    .row
      .col-lg-12
        .form-group
          .control-label.col-sm-2
            = f.label :title
          .col-lg-12.col-sm-6
            = f.text_field :title, class: 'form-control', placeholder: 'Title of post', autofocus: true

    .form-row
      .form-group.col-lg-4
          .control-label.col-sm-2
            = f.label 'Requester'
          .col-lg-12.col-sm-6
            = f.text_field :requester, class: 'form-control', placeholder: 'Enter the requesters name'

      .form-group.col-lg-4
        .control-label.col-sm-2
          = f.label :telephone
        .col-lg-12.col-md-6.col-sm-3
          = f.telephone_field :telephone, class: 'form-control', placeholder: 'Add Requesters telephone number'

      .form-group.col-lg-4
        .control-label.col-lg-4.col-sm-2
          = f.label 'Blood type'
        .col-lg-12.col-md-6.col-sm-3
          = f.select(:bloodtype, options_for_select(bloodytype_select), { include_blank: 'Select your bloodtype'}, { class: 'form-control' })

    .form-group
      .control-label.col-sm-2
        = f.label :description
      .col-sm-6.col-lg-12
        = f.text_area :description, rows: 2, class: 'form-control', placeholder: 'Add any details if any such as address'
    .form-group
      .col-sm-offset-2.col-sm-10
        = f.submit class: 'btn btn-primary btn-large'

app/views/posts/edit.html.slim
h1.text-center
  | Admin can make changes to the post
= render 'form'

= link_to 'Changed my mind', posts_path

app/views/posts/index.html.slim
h1.display-4.text-center.font-weight-bold.mt-5 All posts
- @posts.each do |post|
  .card.mt-5.mb-5
    .card-body.bg-light
      h5.card-title.font-weight-bold.text-center
        = post.title

      .d-flex.div_titles.mt-3
        .div
          h5.card-title.font-weight-bold.float-left
            | Requester:
          h5.card-title.float-left.ml-2
            = post.requester

        .div
          h5.card-title.font-weight-bold.float-left
            | Required BloodType:
          h5.card-title.float-left.ml-2
            = post.bloodtype

        .div
          h5.card-title.font-weight-bold.float-left
            | Donator:
          - if !post.donator.blank?
            h5.card-title.float-left.ml-2
              = post.donator
          - else
            h5.card-title.float-left.ml-2.font-italic
              | No donator selected

      p.card-text.lead
        = truncate(post.description, length: 100)

      .div
        .d-inline-flex.mt-3
          p.float-left.text-muted.mt-1.mr
            = post.comments.count
            |  Comments

          - if current_user.admin?
            p.float-left.text-muted.mt-1.ml-4.mr-auto
              = Volunteer.where(post_id: post).count
              |  Volunteers
        .d-inline-flex.mt-3.float-right
          .button.p-2
            = link_to 'Delete', post_path(post), method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-sm btn-danger float-right'
          .button.p-2
            = link_to 'Show', post_path(post), class: 'btn btn-sm btn-info float-right mr-3'

app/views/posts/new.html.slim
h1.text-center.font-weight-bold
  | Admin can make a new post
= render 'form'

app/views/posts/show.html.slim
h1.display-4.text-center.font-weight-bold.mt-5 Selected Post
.card.bg-secondary.mt-5
  .card-body
    h4.card-title.font-weight-bold.text-center
      = @post.title

    .div.d-flex.justify-content-between.mt-3
      .div
        h5.card-title.font-weight-bold.float-left
          | Requester:
        h5.card-title.float-left.ml-2.text-light
          = @post.requester

      .div
        h5.card-title.font-weight-bold.float-left
          | Telephone Number:
        h5.card-title.float-left.ml-2.text-light
          = @post.telephone

      .div
        h5.card-title.font-weight-bold.float-left
          | Required BloodType:
        h5.card-title.float-left.ml-2.text-light
          = @post.bloodtype

    p.card-text.lead.text-light
      = @post.description

    h5.card-title.font-weight-bold.float-left
      | Donator:
    - if !@post.donator.blank?
      h5.card-title.float-left.ml-2.text-light
        = @post.donator
    - else
      h5.card-title.float-left.ml-2.font-italic.text-light
        | No donator selected

    - if current_user.admin?
      = link_to 'Delete', post_path, method: :delete, data: { confirm: 'Are you sure' }, class: 'btn btn-sm btn-danger float-right'
      = link_to 'Edit the post  ', edit_post_path, class: 'btn btn-sm btn-warning float-right mr-3'

    - if donator_check(@post, current_user)
      br
      br
      .d-flex.align-items-center.flex-column.justify-content-center
        - unless Volunteer.exists?(post_id: @post, user_id: current_user)
          h6.card-title.font-weight-bold
            | Your blood can help save lives
          br
          = link_to 'Volunteer', post_volunteers_path(@post), class: 'btn btn-sm btn-primary float-right mr-3', method: :post, data: { confirm: "Are you want to volunteer to donate blood to #{@post.requester}" }

        - if Volunteer.exists?(post_id: @post, user_id: current_user)
          h6.card-title.font-weight-bold.text-light
            | You have submitted your volunteer request

- if volunteer_show_check(@post, current_user)
  hr
  h3
    strong
      | Available donors to select from
  = render @post.volunteers
  hr

.container.mt-5
  h5
    = @post.comments.count
    |  Comments
  = render @post.comments
  hr
  h3 Leave a reply
  = render 'comments/form'

app/views/posts/specific_indexing.html.slim
h1.display-4.text-center.font-weight-bold.mt-5 All posts
- @posts.each do |post|
  .card.mt-5.mb-5
    .card-body.bg-light
      h5.card-title.font-weight-bold.text-center
        = post.title

      .d-flex.div_titles.mt-3
        .div
          h5.card-title.font-weight-bold.float-left
            | Requester:
          h5.card-title.float-left.ml-2
            = post.requester

        .div
          h5.card-title.font-weight-bold.float-left
            | Required BloodType:
          h5.card-title.float-left.ml-2
            = post.bloodtype

        .div
          h5.card-title.font-weight-bold.float-left
            | Donator:
          - if !post.donator.blank?
            h5.card-title.float-left.ml-2
              = post.donator
          - else
            h5.card-title.float-left.ml-2.font-italic
              | No donator selected

      p.card-text.lead
        = truncate(post.description, length: 100)

      .div
        .d-inline-flex.mt-3
          p.float-left.text-muted.mt-1.ml-2.mr-auto
            = post.comments.count
            |  Comments

        .d-inline-flex.mt-3.float-right
          - if current_user.admin?
            .button
              = link_to 'Delete', post_path(post), method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-sm btn-danger float-right'
          .button
            = link_to 'View Complete Post', post_path(post), class: 'btn btn-sm btn-info float-right mr-3'

      - if donator_check(post, current_user)
        br
        br
        .d-flex.align-items-center.flex-column.justify-content-center
          - unless Volunteer.exists?(post_id: post, user_id: current_user)
            h6.card-title.font-weight-bold
              | Your blood can help save lives
            br
            = link_to 'Volunteer', post_volunteers_path(post), class: 'btn btn-sm btn-primary float-right mr-3', method: :post, data: { confirm: "Are you want to volunteer to donate blood to #{post.requester}" }
          - if Volunteer.exists?(post_id: post, user_id: current_user)
            h6.card-title.font-weight-bold.text-success
              | You have submitted your volunteer request

app/views/volunteers/_volunteer.html.slim
.container.mt-2
  .card.mt-4.bg-light
    .card-body
      .div
        h5.card-title.float-left
          strong
            | Name:
        h5.card-title.ml-1
            = volunteer.user.name

        h5.card-title.float-left
          strong
            | Latest Donation Date:
        h5.card-title.float-left.ml-1
            = volunteer.user.last_donated_date
            em.text-muted.ml-2
              | (
              = time_ago_in_words(volunteer.user.last_donated_date)
              | )

      = link_to 'Select', select_volunteer_path(@post, user_id: volunteer.user, donator: volunteer.user.name, last_donated_date: Date.today), class: 'btn btn-sm btn-primary float-right mr-3', method: :patch, data: { confirm: "Are you sure you want to choose #{volunteer.user.name} as the donor?" }

/ - if volunteer.user == current_user || current_user.admin?
/         a.card-link
/           = link_to 'Delete', [comment.post, comment], method: :delete, data: { confirm: "Are you sure?" }
/ =volunteer.user.name